name: "Publish homework"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
jobs:
  read-repositories-and-lessons:
    name: "Read repositories and lessons"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: "Read repositories and lessons"
        id: repositories-and-lessons
        run: |
          ./gradlew :setup:run --args="$GITHUB_OUTPUT"
    outputs:
      setup: ${{ steps.repositories-and-lessons.outputs.setup }}
  post-homeework:
    name: "Publish homework"
    runs-on: ubuntu-latest
    needs: read-repositories-and-lessons
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.read-repositories-and-lessons.outputs.setup) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Publish required homework"
        run: |
          ./gradlew :homework:run --args="${{ matrix.repository }} ${{ matrix.lesson }}"