name: "Setup repositories"

on:
  workflow_dispatch:
jobs:
  read-repositories:
    name: "Read repositories"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: repositories
        run: "kotlin ./RepositoryMatrix.main.kts >> $GITHUB_OUTPUT"
    outputs:
      repositories: "${{ steps.repositories.outputs.repositories }}"
  setup-repository:
    name: "Setup repository"
    runs-on: ubuntu-latest
    needs: read-repositories
    strategy:
      matrix: "${{ fromJson(needs.read-repositories.outputs.repositories) }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Clone"
        run: "git clone ${{ matrix.repository }}"
      - name: "Step into repository"
        run: "cd $( kotlin ./RepositoryName.main.kts ${{ matrix.repository }} )"
