name: "Setup repositories"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "repositories"
      - "repository/*"
      - "workflows/*"
      - "setup/*"
      - "shared/*"
jobs:
  read-repositories:
    name: "Read repositories"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: "Read repositories"
        id: repositories
        run: |
          ./gradlew :setup:run --args="$GITHUB_OUTPUT"
    outputs:
      setup: ${{ steps.repositories.outputs.setup }}
  setup-repository:
    name: "Setup repository"
    runs-on: ubuntu-latest
    needs: read-repositories
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJson(needs.read-repositories.outputs.setup).repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Update GitHub workflows in the repository"
        run: |
          ./gradlew :repository:run --args="${{ matrix.repository }}"