name: "Setup repositories"
on:
  push:
    branches:
      - main
    paths:
      - "repositories"
      - "workflows/*"
jobs:
  read-repositories:
    name: "Read repositories"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: repositories
        run: "bash ./scripts/setup-repository/repository-matrix.sh >> $GITHUB_OUTPUT"
    outputs:
      repositories: ${{ steps.repositories.outputs.repositories }}
  setup-repository:
    name: "Setup repository"
    runs-on: ubuntu-latest
    needs: read-repositories
    strategy:
      matrix: ${{ fromJson(needs.read-repositories.outputs.repositories) }}
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Update GitHub workflows in the repository"
        id: check-index
        run: "kotlin ./scripts/setup-repository/UpdateGitHubWorflows.main.kts ${{ ${{ matrix.repository }} }} >> $GITHUB_OUTPUT"
      - name: "Push"
        if: steps.check-index.outputs.has-files-to-commit
        run: "git config user.name Xini1"
      - name: "Setup git email"
        if: steps.check-index.outputs.has-files-to-commit
        working-directory: "repository"
        run: "git config user.email tereshchenko.xini@gmail.com"
      - name: "Commit copied GitHub workflows"
        if: steps.check-index.outputs.has-files-to-commit
        working-directory: "repository"
        run: "git commit -m 'GitHub workflows'"
      - name: "Push to the remote repository"
        if: steps.check-index.outputs.has-files-to-commit
        working-directory: "repository"
        run: "git push"