name: "Setup repositories"

on:
  workflow_dispatch:
jobs:
  read-repositories:
    name: "Read repositories"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: repositories
        run: "kotlin ./RepositoryMatrix.main.kts >> $GITHUB_OUTPUT"
    outputs:
      repositories: "${{ steps.repositories.outputs.repositories }}"
  setup-repository:
    name: "Setup repository"
    runs-on: ubuntu-latest
    needs: read-repositories
    strategy:
      matrix: "${{ fromJson(needs.read-repositories.outputs.repositories) }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Clone the repository"
        run: "git clone ${{ matrix.repository }}"
      - name: "Step into the repository"
        run: "cd $( kotlin ./RepositoryName.main.kts ${{ matrix.repository }} )"
      - name: "Create branch 'setup'"
        run: "git checkout -b setup"
      - name: "Copy GitHub workflows to the repository"
        run: "mkdir ./.github && cp -r ./templates ./.github/workflows"
      - name: "Add copied GitHub workflows to the index"
        run: "git add ./.github"
      - name: "Commit copied GitHub workflows"
        run: "git commit -m 'GitHub workflows'"
      - name: "Push the branch"
        run: "git push origin -u setup"