name: "Setup repositories"

on:
  workflow_dispatch:
jobs:
  read-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Read repositories"
        id: repositories
        run: kotlin ./RepositoryMatrix.main.kts
    outputs:
      repositories: "${{ steps.read-repositories.outputs.repositories }}"
  clone-repositories:
    runs-on: ubuntu-latest
    needs: "read-repositories"
    strategy:
      matrix:
        repository: "${{ fromJson(needs.read-repositories.outputs.repositories) }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Echo"
        run: "echo ${{ matrix.repository }}"